
server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: producer-gateway   #路由的id，唯一
        uri: lb://producer     #服务名
        #uri: localhost:8201   地址
        predicates:            #断言，路径匹配的转发到响应的uri对应服务下路径
          - Path=/producer/**

eureka:
  instance:
    appname: gateway
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
