#port
server:
  port: 8303

#eureka
eureka:
  instance:
    appname: consumer-hystrix
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#hystrix
feign:
  hystrix:
    enabled: true
