#port
server:
  port: 8201
# 服务名：application-name 比instance-appname 优先级更高
spring:
  application:
    name: producer

eureka:
  instance:
    appname: producer
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

