#port
server:
  port: 8501
#配置name
spring:
  application:
    name: config-server
  #配置yml的git路径
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rainscloud/spring-cloud-demo.git
          username: rainscloud
          password:
  rabbitmq:
    host: 192.168.50.90 # rabbitmq主机
    port: 5672      # rabbitmq端口，注意是5672而不是15672
    username: admin # 用户名
    password: admin # 密码

management:
  endpoints:
    web:
      exposure:
        include: '*'



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka





