#port
server:
  port: 8501
#name
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com.cnpmjs.org/rainscloud/spring-cloud-demo.git
          username:
          password:
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
